### ISSUE TITLE
ERROR : Duplicate registration for NetFn [0x6], Cmd:[0xFF] 

### ISSUE THREAD

**Issue by causten** [openbmc/phosphor-host-ipmid#61]
I'm seeing this in tag 4 builds.  Not sure how far back it goes.

**Comment by anoo1** [comment]
This was introduced with the 'warm reset' app handler command. Because it was created in a separate library per requirement, it's registering an app handler wildcard but that app handler wildcard is already registered in the app handler library. I've patched a system with the fix of removing the duplicated registration and verified this error does not cause any issues in the ipmi daemon. We'll fix this month.

**Comment by nkskjames** [comment]
Fixed by https://github.com/openbmc/phosphor-host-ipmid/pull/67
