### ISSUE TITLE
Issues with commit 13fb441

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/phosphor-host-ipmid#80]
There are two issues with commit 13fb441 that escaped the code review process:

1.

https://github.com/openbmc/phosphor-host-ipmid/commit/13fb441467d9c2aa22910ee8f2bbb3e373066f64?diff=unified#diff-87a9c9a47212626ff55cd8c4b1378ae4L360

The comment indicates "we only support channel 1" but this code changed added support for "channel 8".  Need the comment correctly updated.

Is there any reason why we are not allowing any channel?

2.

https://github.com/openbmc/phosphor-host-ipmid/commit/13fb441467d9c2aa22910ee8f2bbb3e373066f64?diff=unified#diff-44d0d8d3be3e961e202a4ab3f261859bL270

This change removed the 'return -1' from this function, which is obviously an error path.  I suspect this was done because messages were never responded to in the error path and left "hanging" until timeout.  But, this change is not the appropriate one either.  We now are responding with a response data in undetermined state.  If we are going to respond after an error by the ipmi-plugin we need to have a well-defined error response.

**Comment by mdmillerii** [comment]
1. My understanding is the channel indicates the interface to use, and if we allow any channel we would not be able to support setting a separate mac on a second interface in the future.

2. As you state both are wrong.  The return was recently added in 1eaea4f4c39f775a04efd2ae504f241e01877882 and resulted in no reply being generated hanging all ipmi traffic.  The diff was a revert to the prior behavior.

**Comment by vishwabmc** [comment]
Tom and I have discussed about this and this has 2 parts into it :

The comment indicates "we only support channel 1" but this code changed added support for "channel 8". Need the comment correctly updated.
---------------------------------------------------
>> Tom will use this issue and fix.
--------------------------------------------------

13fb441?diff=unified#diff-44d0d8d3be3e961e202a4ab3f261859bL270
>> There is a github issue to address these at a global scope and it is : 
https://github.com/openbmc/phosphor-host-ipmid/issues/78 
-and-
https://github.com/openbmc/phosphor-host-ipmid/issues/77

------- 

I am unable to move this to Tom since I dont have the access. Please move it to Tom.

**Comment by anoo1** [comment]
@tomjoseph83 will take a look.
