### ISSUE TITLE
BMC version should be BCD encoded

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/phosphor-host-ipmid#89]
According to IPMI spec, Firmware revision 2 has to be BCD encoded. For example, currently, if we set version to 11 in revision 2, version will show B not 11 as expected.

**Comment by anoo1** [comment]
The code seems to be working correctly. The version property is represented as a string of decimal numbers. So to get a version of "11 BCD" (binary 0001 0001) in the response packet, need to set the version to 17 decimal (0x11).
Trying some corner cases like setting version to v255.255 looks it's handling correctly as well, the response packet is "data:  [0x00, 0x00, 0x7f, 0xff, 0x02,...". So the code is chopping off the 8th bit of the major firmware version since that's reserved so 255 (0xff) becomes 0x7f, and displays the minor as 0xff as expected.

**Comment by johnhcwang** [comment]
It'll get confusion if the tag name is not the same as version in response data.
For example that you mentioned above, the user/designer get the version 0.11 on a failure board and want to track the source code in the tag from GitHub. They won't find out 0.11 tag name in this case. The tag name on GitHub is 0.17 actually.

**Comment by anoo1** [comment]
After consulting with the team, this issue is valid, the format of the minor version should translate from decimal 10 to 0x10 to make it BCD encoded. We'll be making a change for this.

**Comment by anoo1** [comment]
PR: https://github.com/openbmc/phosphor-host-ipmid/pull/94

IPMI Spec:
byte 4 : [0:6] Major Firmware Revision, binary encoded.
byte 5 : Minor Firmware Revision, BCD encoded.

Verification:
Setting version to: "v11.10-4-gd8cd888-dirty"
 
IPMI raw response (0x0b 0x10):
00 00 00 0b 10 02 0d 41 a7 00 43 40 00 04 01 00

ipmitool response:
# ipmitool mc info
Device ID                 : 0
Device Revision           : 0
Firmware Revision         : 11.10
