### ISSUE TITLE
BMC aux revision doesn't match with the aux number in tag

### ISSUE THREAD

**Issue by johnhcwang** [openbmc/phosphor-host-ipmid#96]
Reproduce:
Setting tag version in /etc/os-release to: "v1.0.**11**-dirty"

IPMI raw response:
00 00 00 01 00 02 0d 41 a7 00 43 40 00 **0b** 01 00

It'll get confusion when user/designer get the version 1.0.B on a failure board and want to track the source code from the tag on GitHub. They can't find out the tag 1.0.B.
Should we get the improvement on this situation?

**Comment by ruscur** [comment]
Hi,

These are hexadecimal numbers.  0b in hex is equivalent to 11 in decimal.  The reason raw data is paired into sets of two hexadecimal digits is because these sets represent one byte.

If you're unfamiliar with hexadecimal see [here](https://simple.wikipedia.org/wiki/Hexadecimal_numeral_system).

I don't think this is a bug - most people looking at raw data are going to be aware that it's in hex and make the appropriate conversion.  The version tag could be changed to use hexadecimal instead so that the numbers were equivalent, but that goes against long-standing versioning convention.

**Comment by anoo1** [comment]
Checking the IPMI spec, it specifies the aux field as hex number.
Perhaps the ipmitool displays the information in a clearer way. If you'd try running the command "ipmitool mc info" from petitboot or host, it should display the aux info specifying it's a hex number:
Firmware Revision           : 1.0
Aux Firmware Rev Info    :  0x0b

**Comment by johnhcwang** [comment]
Yes, I know the aux field should be hex number in IPMI and the versioning convention in obmc.
I just want to highlight this confusion when user get the version 1.0.b by ipmi on failure system, but he may not find out this tag because unfamiliar with obmc versioning convention.

**Comment by johnhcwang** [comment]
Sorry to disturb you guys.
I think you're correct because this situation also appeared with major field.
I mean the version will be **a**.0.b by ipmi if tag name is v10.0.11.
So we shouldn't consider the confusion that I said.
Please waive this issue.
